(ns mg-webpage.models.england
  (:use hiccup.core)
  (:require [mg-webpage.models.common :as common]))

(def england-page
  (html [:html
         [:head [:link {:href "/css/screen.css", :rel "stylesheet", :type "text/css"}]]
         [:body
          common/navbar
          [:h2.highlighter  [:span.titles [:span.bar] "England"]]
          [:p ""]
          [:h2.highlighter [:span.titles [:span.bar] "Bath"]]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england26.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england28.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england29.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england31.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england32.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england33.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england34.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england35.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england37.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england38.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england39.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england40.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england41.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england42.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england43.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england44.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england65.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england66.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england67.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england68.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england70.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england71.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england73.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england74.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england95.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england96.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england97.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england98.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england99.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england100.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england101.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england102.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england103.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england107.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england108.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england109.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england110.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england111.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england112.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england113.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england114.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england115.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england135.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england136.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england137.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england138.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england139.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england140.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england141.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england142.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england143.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england144.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england146.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england147.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england148.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england149.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england150.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england151.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england152.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england153.jpg"}]
          [:h2.highlighter [:span.titles [:span.bar] "London"]]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england1.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england2.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england3.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england4.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england5.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england6.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england8.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england9.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england13.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england14.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england15.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england16.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england17.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england18.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england19.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england21.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england22.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england24.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england79.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england80.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england83.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england84.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england88.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england89.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england91.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england92.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england117.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england118.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england119.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england121.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england122.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england123.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england124.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england126.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england127.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england128.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england129.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england130.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england131.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england132.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england134.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england77.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england116.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england160.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england155.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england156.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england157.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england158.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england133.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/england159.jpg"}]]]))
