(ns mg-webpage.models.italy
  (:use hiccup.core)
  (:require [mg-webpage.models.common :as common]))

(def italy-page
  (html [:html
         [:head [:link {:href "/css/screen.css", :rel "stylesheet", :type "text/css"}]]
         [:body
          common/navbar
          [:h2.highlighter  [:span.titles [:span.bar] "Italy"]]
          [:p ""]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/italy1.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/italy2.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/italy3.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/italy4.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/italy5.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/italy6.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/italy7.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/italy8.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/italy9.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/italy10.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/italy11.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/italy12.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/italy13.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/italy14.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/italy15.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/italy16.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/italy17.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/italy18.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/italy19.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/italy20.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/italy21.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/italy22.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/italy23.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/italy24.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/italy25.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/italy26.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/italy27.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/italy28.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/italy29.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/italy30.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/italy31.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/italy32.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/italy33.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/italy34.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/italy35.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/italy36.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/italy37.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/italy38.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/italy39.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/italy40.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/italy41.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/italy42.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/italy43.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/italy44.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/italy45.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/italy46.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/italy47.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/italy48.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/italy49.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/italy50.jpg"}]]]))
