(ns mg-webpage.models.jordan
  (:use hiccup.core)
  (:require [mg-webpage.models.common :as common]))

(def jordan-data
  "jordan" {:title "Jordan"
            :description ""
            :panoramic ["https://s3-us-west-1.amazonaws.com/mgsite-media/jordan6.jpg" "https://s3-us-west-1.amazonaws.com/mgsite-media/jordan7.jpg" "https://s3-us-west-1.amazonaws.com/mgsite-media/jordan8.jpg" "https://s3-us-west-1.amazonaws.com/mgsite-media/jordan9.jpg" "https://s3-us-west-1.amazonaws.com/mgsite-media/jordan10.jpg" "https://s3-us-west-1.amazonaws.com/mgsite-media/jordan11.jpg" "https://s3-us-west-1.amazonaws.com/mgsite-media/jordan12.jpg"]
            :images []
            })

(defn jordan-page [jordan-data]
  (html [:html
         [:head [:link {:href "/css/screen.css", :rel "stylesheet", :type "text/css"}]]
         [:body
          common/navbar
          [:h2.highlighter  [:span.titles [:span.bar] "Jordan"]]
          [:p ""]
          [:img.place-image {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/jordan6.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/jordan1.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/jordan14.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/jordan58.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/jordan60.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/jordan65.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/jordan67.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/jordan29.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/jordan28.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/jordan16.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/jordan80.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/jordan81.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/jordan82.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/jordan26.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/jordan19.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/jordan77.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/jordan32.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/jordan33.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/jordan34.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/jordan35.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/jordan36.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/jordan37.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/jordan38.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/jordan39.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/jordan40.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/jordan42.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/jordan43.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/jordan44.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/jordan73.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/jordan74.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/jordan75.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/wadirum.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/jordan5.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/jordan21.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/jordan22.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/jordan46.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/jordan47.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/jordan49.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/jordan50.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/jordan51.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/jordan53.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/jordan54.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/jordan56.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/jordan57.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/jordan68.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/jordan69.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/jordan70.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/jordan71.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/jordan20.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/jordan72.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/jordan24.jpg"}]
          [:img.images {:src "https://s3-us-west-1.amazonaws.com/mgsite-media/jordan27.jpg"}]]]))
